version: "3.8"
services:
  socket-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    restart: always
  
  socket-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    restart: always
